### ISSUE TITLE
Inclusion of prometheus leading to socket.error

### ISSUE THREAD

**Issue by Brian-Myers-Bose** [MinimalCompact/thumbor#85] opened 2020-08-20 16:20 UTC
I can't believe no one else hasn't run into this, but I'm failing to find a reference.

Included in docker-compose.yml
```PROMETHEUS_SCRAPE_PORT: "8000"```

Inclusion of 
```METRICS: "tc_prometheus.metrics.prometheus_metrics"```
in my docker-compose.yml results in metrics being displayed at localhost:8000/metrics, but I also get errors in my logs.
```

thumbor_1  | Traceback (most recent call last):
thumbor_1  |   File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
thumbor_1  |     "__main__", fname, loader, pkg_name)
thumbor_1  |   File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
thumbor_1  |     exec code in run_globals
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/thumbor/server.py", line 154, in <module>
thumbor_1  |     main(sys.argv[1:])
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/thumbor/server.py", line 145, in main
thumbor_1  |     with get_context(server_parameters, config, importer) as context:
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/thumbor/server.py", line 104, in get_context
thumbor_1  |     importer=importer
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/thumbor/context.py", line 43, in __init__
thumbor_1  |     self.metrics = importer.metrics(config)
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/tc_prometheus/metrics/prometheus_metrics.py", line 19, in __init__
thumbor_1  |     start_http_server(config.PROMETHEUS_SCRAPE_PORT)
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/prometheus_client/exposition.py", line 193, in start_http_server
thumbor_1  |     httpd = _ThreadingSimpleServer((addr, port), CustomMetricsHandler)
thumbor_1  |   File "/usr/local/lib/python2.7/SocketServer.py", line 420, in __init__
thumbor_1  |     self.server_bind()
thumbor_1  |   File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
thumbor_1  |     SocketServer.TCPServer.server_bind(self)
thumbor_1  |   File "/usr/local/lib/python2.7/SocketServer.py", line 434, in server_bind
thumbor_1  |     self.socket.bind(self.server_address)
thumbor_1  |   File "/usr/local/lib/python2.7/socket.py", line 228, in meth
thumbor_1  |     return getattr(self._sock,name)(*args)
thumbor_1  | socket.error: [Errno 98] Address already in use

```
Removal of this env var results in localhost:8000/metrics showing "This page isn't working", but in DEBUG mode I can see thumbor metrics 
```
thumbor_1  | 2020-08-20 16:16:31 thumbor:DEBUG METRICS: timing: response.time:1127
thumbor_1  | 2020-08-20 16:16:31 thumbor:DEBUG METRICS: timing: response.time.304:1127
thumbor_1  | 2020-08-20 16:16:31 thumbor:DEBUG METRICS: inc: response.status.304:1
thumbor_1  | 2020-08-20 16:16:31 thumbor:DEBUG METRICS: inc: response.format.webp:1
thumbor_1  | 2020-08-20 16:16:31 thumbor:DEBUG METRICS: timing: response.time.webp:1127
thumbor_1  | 2020-08-20 16:16:31 thumbor:DEBUG METRICS: inc: response.bytes.webp:8942
```
Has anyone else run into this?

**Comment by gingerlime** [comment] 2020-08-20 17:10
Het @Brian-Myers-Bose 👋 

I've never used prometheus, so not sure I can help much. Would you like to post a sample docker-compose.yml file that reproduces the issue you're experiencing? this can certainly help troubleshooting things.

**Comment by Brian-Myers-Bose** [comment] 2020-08-20 17:13
Btw.  I changed my Dockerfile to 
```
#FROM minimalcompact/thumbor:6.7.0
FROM apsl/thumbor:latest

RUN pip install --upgrade pip \
# \
#    && pip install tc_redis
    && pip install tc_prometheus
# ENV LOG_LEVEL DEBUG
```
and it worked first time.

**Comment by gingerlime** [comment] 2020-08-20 17:15
Looks like the Dockerfile is based on apsl/thumbor, so I'm not sure I can help with that one.

btw, did you check that nothing else is binding to port 8000 on your machine? either a local service that listens on it, or another docker container with an exposed port?

**Comment by gingerlime** [comment] 2020-08-20 17:25
I tried to test it as well, and I'm seeing the same issue. I tried different ports, but it seems to always happen.

Perhaps worth asking on https://github.com/thumbor-community/prometheus ? maybe it's being started more than once? (just a guess, I don't really know).

@kkopachev is this something you could maybe help with?

**Comment by Brian-Myers-Bose** [comment] 2020-08-20 17:29
@gingerlime Thanks for taking a look.  This only appears to be an issue with minimalCompact where the plug-in is included by default.  When one moves to another build where one must install plugins, it works.  I have run ```netstat -an | grep LISTEN``` and don't appear to have anything else listening on 8000.

**Comment by gingerlime** [comment] 2020-08-20 17:37
very strange... your guess is as good as (or perhaps better than) mine. It was added last year and seemed to have worked? https://github.com/MinimalCompact/thumbor/pull/38#issuecomment-515770447 but not sure what changed that could break it ... maybe try a few older versions to try to pinpoint what changed caused it to start behaving this way?

**Comment by gingerlime** [comment] 2020-10-28 06:03
It's not really resolved, but I'll close this for now, given that there isn't much we can do at the moment.

**Closed by gingerlime** 2020-10-28 06:03 UTC
